#!/bin/bash
ONLINE = 0
wrapdocker &
sleep 5
cd /home/docker/ && docker-compose build && docker-compose up &
ONLINE=0; while [ $ONLINE == 0 ]; do  curl -s localhost | head -n 1 | grep DOCTYPE; rc=$?; if [ $rc == 0 ]; then ONLINE=1; else echo "We keep on waiting (waiting) waiting on the page to load"; fi; sleep 25; done
docker exec docker_web_1 bundle exec rake db:create db:setup db:migrate RAILS_ENV=production
docker inspect --format '{{ .NetworkSettings.IPAddress }}' "docker_web_1" | xargs -I % iptables -t nat -A DOCKER -p tcp --dport 8080 -j DNAT --to-destination %:80
wait